# Generated by Django 5.1.4 on 2024-12-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='elo',
            field=models.IntegerField(default=0),
        ),
    ]
